#ifndef PHASE_H
#define PHASE_H

#include "stm32f446xx.h"
	//TIM1->CCER |= TIM_CCER_CC1E; // output enable
	//TIM1->CCER |= TIM_CCER_CC1NE; // complementary output enable

#define A_HI_ON TIM1->CCER |= TIM_CCER_CC1E//GPIOA->ODR = GPIO_ODR_8
#define B_HI_ON TIM1->CCER |= TIM_CCER_CC2E//GPIOA->ODR = GPIO_ODR_9
#define C_HI_ON TIM1->CCER |= TIM_CCER_CC3E//GPIOA->ODR = GPIO_ODR_10

#define A_LO_ON TIM1->CCER |= TIM_CCER_CC1NE//GPIOB->ODR = GPIO_ODR_13
#define B_LO_ON TIM1->CCER |= TIM_CCER_CC2NE//GPIOB->ODR = GPIO_ODR_14
#define C_LO_ON TIM1->CCER |= TIM_CCER_CC3NE//GPIOB->ODR = GPIO_ODR_15

#define A_HI_OFF TIM1->CCER &= ~TIM_CCER_CC1E//GPIOA->ODR = GPIO_ODR_8
#define B_HI_OFF TIM1->CCER &= ~TIM_CCER_CC2E//GPIOA->ODR = GPIO_ODR_9
#define C_HI_OFF TIM1->CCER &= ~TIM_CCER_CC3E//GPIOA->ODR = GPIO_ODR_10

#define A_LO_OFF TIM1->CCER &= ~TIM_CCER_CC1NE//GPIOB->ODR = GPIO_ODR_13
#define B_LO_OFF TIM1->CCER &= ~TIM_CCER_CC2NE//GPIOB->ODR = GPIO_ODR_14
#define C_LO_OFF TIM1->CCER &= ~TIM_CCER_CC3NE//GPIOB->ODR = GPIO_ODR_15

#define ALL_HI_OFF A_HI_OFF;B_HI_OFF;C_HI_OFF;//GPIOA->ODR = 0
#define ALL_LO_OFF A_LO_OFF;B_LO_OFF;C_LO_OFF;//GPIOB->ODR = 0


#define A_B ( TIM_CCER_CC1E | TIM_CCER_CC2NE | TIM_CCER_CC1P | TIM_CCER_CC1NP | TIM_CCER_CC2P | TIM_CCER_CC2NP | TIM_CCER_CC3P | TIM_CCER_CC3NP ) // 0b101011101011 //  
#define A_C ( TIM_CCER_CC1E | TIM_CCER_CC3NE | TIM_CCER_CC1P | TIM_CCER_CC1NP | TIM_CCER_CC2P | TIM_CCER_CC2NP | TIM_CCER_CC3P | TIM_CCER_CC3NP ) // 0b111010101011 //  
#define B_C ( TIM_CCER_CC2E | TIM_CCER_CC3NE | TIM_CCER_CC1P | TIM_CCER_CC1NP | TIM_CCER_CC2P | TIM_CCER_CC2NP | TIM_CCER_CC3P | TIM_CCER_CC3NP ) // 0b111010111010 //  
#define B_A ( TIM_CCER_CC2E | TIM_CCER_CC1NE | TIM_CCER_CC1P | TIM_CCER_CC1NP | TIM_CCER_CC2P | TIM_CCER_CC2NP | TIM_CCER_CC3P | TIM_CCER_CC3NP ) // 0b101010111110 //  
#define C_A ( TIM_CCER_CC3E | TIM_CCER_CC1NE | TIM_CCER_CC1P | TIM_CCER_CC1NP | TIM_CCER_CC2P | TIM_CCER_CC2NP | TIM_CCER_CC3P | TIM_CCER_CC3NP ) // 0b101110101110 //  
#define C_B ( TIM_CCER_CC3E | TIM_CCER_CC2NE | TIM_CCER_CC1P | TIM_CCER_CC1NP | TIM_CCER_CC2P | TIM_CCER_CC2NP | TIM_CCER_CC3P | TIM_CCER_CC3NP ) // 0b101111101010 //  

#endif
